-- Copie e cole este código no SQL Editor do Supabase para criar a tabela necessária
-- Este SQL está alinhado com o código da aplicação (shared/schema.ts)

create table reports (
  id bigint generated by default as identity primary key,
  protocol text unique not null,
  type text not null check (type in ('text', 'audio', 'image', 'video')),
  category text not null default 'Solicitação',
  content text,
  media_url text,
  latitude text,
  longitude text,
  address text,
  is_anonymous boolean default false not null,
  status text default 'received' not null,
  created_at timestamp with time zone default now() not null
);

-- Habilitar Row Level Security (RLS) - Recomendado
alter table reports enable row level security;

-- Política de segurança: Permitir que qualquer pessoa (pública/anônima) INSERIR dados
create policy "Enable insert for public" on reports for insert with check (true);

-- Política de segurança: Permitir leitura apenas pelo protocolo (opcional, pode ser restrito)
-- create policy "Enable select for public" on reports for select using (true);
