-- ATENÇÃO: Rode este SQL no Supabase para garantir que o envio funcione conforme o novo código.
-- O sistema mudou para usar a tabela 'manifestacoes' (nomes em português conforme código fornecido).

create table manifestacoes (
  id bigint generated by default as identity primary key,
  protocolo text unique not null,
  tipo_manifestacao text not null check (tipo_manifestacao in ('text', 'audio', 'image', 'video')),
  category text default 'Solicitação',    -- Categoria: Denúncia, Elogio, etc.
  relato text,                            -- Conteúdo em texto
  media_url text,                         -- Link para arquivo de midia
  latitude text,                          -- Localização GPS
  longitude text,
  address text,                           -- Endereço digitado
  is_anonimo boolean default false not null,
  status text default 'recebido' not null,
  created_at timestamp with time zone default now() not null
);

-- Habilitar Row Level Security (RLS) - Recomendado
alter table manifestacoes enable row level security;

-- Política de segurança: Permitir que qualquer pessoa (pública/anônima) INSERIR dados
create policy "Permitir inserção pública" on manifestacoes for insert with check (true);

-- Política de leitura (opcional, se quiser consultar depois):
create policy "Permitir leitura pública" on manifestacoes for select using (true);
